# The time in seconds to wait before booting the default entry
timeout: 5

# The entry name that will appear in the boot menu
/Vibe Recovery (1080p)
    # The protocol we are using (Revision 3/10 compliant)
    protocol: limine

    # Path to the kernel within the ISO. 
    # 'boot():' refers to the partition the bootloader started from.
    path: boot():/vibe_kernel.elf

/Vibe Recovery (Safe Graphics)
    protocol: limine
    path: boot():/vibe_kernel.elf
    resolution: 800x600x32
